language: python
python:
  - '3.8'
sudo: false

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  global:
    - PGPORT=5433
    - POSTGRES_PORT=5433
  matrix:
  - TOXENV=codestyle
  - TOXENV=main

services:
  - redis-server
  - postgresql

cache:
  apt: true
  pip: true

install:
  - pip install tox
  - make develop

before_script:
  - psql -c 'create database scraper;' -U postgres

script:
  - RUNNING_IN_CI=True tox -v
