# Generated by Django 3.0.3 on 2020-02-26 19:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "New"),
                            (2, "Running"),
                            (3, "Aborted"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "html_version",
                    models.CharField(
                        choices=[
                            ("html5", "HTML 5"),
                            ("html4-strict", "HTML 4.01 Strict"),
                            ("html4-transitional", "HTML 4.01 Transitional"),
                            ("html4-frameset", "HTML 4.01 Frameset"),
                            ("xhtml10-strict", "XHTML 1.0 Strict"),
                            ("xhtml10-transitional", "XHTML 1.0 Transitional"),
                            ("xhtml10-frameset", "XHTML 1.0 Frameset"),
                            ("xhtml-11", "XHTML 1.1"),
                        ],
                        max_length=256,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("headings", django.contrib.postgres.fields.jsonb.JSONField()),
                ("internal_links", models.PositiveIntegerField(default=0)),
                ("external_links", models.PositiveIntegerField(default=0)),
                ("broken_links", models.PositiveIntegerField(default=0)),
                ("contained_login_form", models.BooleanField(default=False)),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            (100, "Continue"),
                            (101, "Switching Protocols"),
                            (102, "Processing"),
                            (103, "Early Hints"),
                            (200, "OK"),
                            (201, "Created"),
                            (202, "Accepted"),
                            (203, "Non Authoritative Information"),
                            (204, "No Content"),
                            (205, "Reset Content"),
                            (206, "Partial Content"),
                            (207, "Multi Status"),
                            (208, "Already Reported"),
                            (226, "IM Used"),
                            (300, "Multiple Choices"),
                            (301, "Moved Permanently"),
                            (302, "Found"),
                            (303, "See Other"),
                            (304, "Not Modified"),
                            (305, "Use Proxy"),
                            (306, "Switch Proxy"),
                            (307, "Temporary Redirect"),
                            (308, "Permanent Redirect"),
                            (400, "Bad Request"),
                            (401, "Unauthorized"),
                            (402, "Payment Required"),
                            (403, "Forbidden"),
                            (404, "Not Found"),
                            (405, "Method Not Allowed"),
                            (406, "Not Acceptable"),
                            (407, "Proxy Authentication Required"),
                            (408, "Request Timeout"),
                            (409, "Conflict"),
                            (410, "Gone"),
                            (411, "Length Required"),
                            (412, "Precondition Failed"),
                            (413, "Request Entity Too Large"),
                            (414, "Request URI Too Long"),
                            (415, "Unsupported Media Type"),
                            (416, "Requested Range Not Satisfiable"),
                            (417, "Expectation Failed"),
                            (418, "I'm a teapot"),
                            (421, "Misdirected Request"),
                            (422, "Unprocessable Entity"),
                            (423, "Locked"),
                            (424, "Failed Dependency"),
                            (425, "Too Early"),
                            (426, "Upgrade Required"),
                            (428, "Precondition Required"),
                            (429, "Too Many Requests"),
                            (431, "Request Header Fields Too Large"),
                            (449, "Retry With"),
                            (451, "Unavailable For Legal Reasons"),
                            (500, "Internal Server Error"),
                            (501, "Not Implemented"),
                            (502, "Bad Gateway"),
                            (503, "Service Unavailable"),
                            (504, "Gateway Timeout"),
                            (505, "HTTP Version Not Supported"),
                            (506, "Variant Also Negotiates"),
                            (507, "Insufficient Storage"),
                            (508, "Loop Detected"),
                            (510, "Not Extended"),
                            (511, "Network Authentication Failed"),
                        ],
                        max_length=256,
                    ),
                ),
            ],
        ),
    ]
