# Generated by Django 3.0.3 on 2020-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("next_scraper", "0002_auto_20200226_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="celery_group_id",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
