# Generated by Django 3.0.3 on 2020-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("next_scraper", "0003_report_celery_group_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="contained_login_form",
            new_name="contains_login_form",
        ),
        migrations.AlterField(
            model_name="report",
            name="html_version",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("html5", "HTML 5"),
                    ("html4-strict", "HTML 4.01 Strict"),
                    ("html4-transitional", "HTML 4.01 Transitional"),
                    ("html4-frameset", "HTML 4.01 Frameset"),
                    ("xhtml10-strict", "XHTML 1.0 Strict"),
                    ("xhtml10-transitional", "XHTML 1.0 Transitional"),
                    ("xhtml10-frameset", "XHTML 1.0 Frameset"),
                    ("xhtml-11", "XHTML 1.1"),
                ],
                max_length=256,
            ),
        ),
    ]
