# Generated by Django 3.0.3 on 2020-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("next_scraper", "0005_auto_20200227_1219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="contains_login_form",
            new_name="may_contain_login_form",
        ),
    ]
