# Generated by Django 3.0.3 on 2020-02-27 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("next_scraper", "0006_auto_20200227_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="original_url",
            field=models.URLField(unique=True),
        ),
    ]
